# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install .net 6.0
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.x

      # Runs a set of commands using the runners shell
      - name: Build app
        run: dotnet build -c Release
        
      - name: Test app
        run: dotnet test
        
      - name: Pack app
        run: dotnet pack -c Release
        
      - name: Push pack to nuget.org
        run: dotnet nuget push "/MoneyExtension/bin/Release/*.nupkg" --api-key ${{ secrets.APIKEY_NUGET }} --source https://api.nuget.org/v3/index.json
